version: '2'
services:
  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postman_dev
  web:
    build: .
    command: npm run start:${ENV}
    image: taylonr/postman
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db