version: '2'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
  web:
    build: .
    command: mix phx.server
    image: taylonr/postman
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db